FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_1.20 AS builder
WORKDIR /go/src/github.com/stolostron/cluster-imageset-controller
COPY . .
ENV GO_PACKAGE github.com/stolostron/cluster-imageset-controller

# Build
RUN make build --warn-undefined-variables

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

# Add the binaries
COPY --from=builder /go/src/github.com/stolostron/cluster-imageset-controller/bin/clusterimageset .
